"""Simulation process: steps physics, publishes observations, consumes action chunks.

Runs the control loop at env_config.yaml's control_hz. Physics never waits for
policy inference (see README architecture): each control step applies whatever
action is currently active -- a slice of the newest received ActionChunk, or a
safe fallback (hold the last commanded action) if nothing fresh enough has
arrived.
"""

from __future__ import annotations

import argparse
import logging
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import yaml

# `generated/` (protoc output) isn't a declared package in pyproject.toml --
# it's regenerated by scripts/compile_proto.sh, not installed -- so running
# this file directly (`python scripts/run_sim.py`, as the README documents)
# needs the repo root on sys.path explicitly. `python -m` would add it
# automatically via cwd, but a plain script invocation only adds its own
# directory (scripts/), not the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sim.mujoco_env import MujocoManipulationEnv
from sim.zmq_publisher import ActionChunkSubscriber, ObservationPublisher, now_us

logger = logging.getLogger("run_sim")

BLEND_STEPS = 4  # control steps to ramp into a newly arrived chunk
MAX_ACTION_AGE_US = 500_000  # 0.5s: older than this without a new chunk -> fallback


class ActionChunkPlayer:
    """Tracks the active ActionChunk and produces one action per control step.

    Handles the two behaviors the README calls out explicitly: blending a
    newly arrived chunk into the one currently playing instead of jumping
    discontinuously, and falling back to holding the last commanded action
    when nothing fresh enough has arrived.
    """

    def __init__(self, action_dim: int) -> None:
        self.action_dim = action_dim
        self._last_action = np.zeros(action_dim, dtype=np.float32)
        self._chunk: dict[str, Any] | None = None
        self._chunk_step = 0
        self._blend_remaining = 0
        self.fallback_steps = 0

    def offer(self, chunk: dict[str, Any] | None) -> None:
        if chunk is None:
            return
        if self._chunk is not None and chunk["frame_id"] <= self._chunk["frame_id"]:
            return  # stale relative to what's already playing
        self._chunk = chunk
        self._chunk_step = 0
        self._blend_remaining = min(BLEND_STEPS, chunk["horizon"])

    def next_action(self) -> tuple[np.ndarray, bool]:
        """Returns (action, is_fallback)."""
        now = now_us()
        chunk_usable = (
            self._chunk is not None
            and self._chunk_step < self._chunk["horizon"]
            and (now - self._chunk["timestamp_us"]) <= MAX_ACTION_AGE_US
        )
        if not chunk_usable:
            self.fallback_steps += 1
            return self._last_action, True

        target = self._chunk["actions"][self._chunk_step]
        if self._blend_remaining > 0:
            alpha = (BLEND_STEPS - self._blend_remaining + 1) / BLEND_STEPS
            action = (1 - alpha) * self._last_action + alpha * target
            self._blend_remaining -= 1
        else:
            action = target
        self._chunk_step += 1
        self._last_action = action.astype(np.float32)
        return self._last_action, False

    @property
    def action_age_ms(self) -> float:
        if self._chunk is None:
            return float("inf")
        return (now_us() - self._chunk["timestamp_us"]) / 1_000


def run(config: dict[str, Any], max_steps: int | None = None) -> None:
    env = MujocoManipulationEnv(config)
    ipc_cfg = config["ipc"]
    obs_pub = ObservationPublisher(
        ipc_cfg["observations"], high_water_mark=ipc_cfg["high_water_mark"]
    )
    action_sub = ActionChunkSubscriber(
        ipc_cfg["actions"], high_water_mark=ipc_cfg["high_water_mark"]
    )
    player = ActionChunkPlayer(action_dim=env.action_space.shape[0])

    control_period = 1.0 / config["control_hz"]
    obs, _ = env.reset()
    obs_pub.send(obs)

    step = 0
    last_log = time.perf_counter()
    steps_since_log = 0
    try:
        while max_steps is None or step < max_steps:
            loop_start = time.perf_counter()

            player.offer(action_sub.recv(timeout_ms=0))
            action, is_fallback = player.next_action()

            obs, _reward, terminated, truncated, _info = env.step(action)
            obs_pub.send(obs)

            step += 1
            steps_since_log += 1
            if terminated or truncated:
                obs, _ = env.reset()
                obs_pub.send(obs)

            now = time.perf_counter()
            if now - last_log >= 1.0:
                achieved_hz = steps_since_log / (now - last_log)
                logger.info(
                    "control_hz=%.1f frame_id=%d action_age_ms=%.1f mode=%s fallback_steps=%d",
                    achieved_hz,
                    obs["frame_id"],
                    player.action_age_ms,
                    "fallback" if is_fallback else "predicted",
                    player.fallback_steps,
                )
                last_log, steps_since_log = now, 0

            sleep_for = control_period - (time.perf_counter() - loop_start)
            if sleep_for > 0:
                time.sleep(sleep_for)
    except KeyboardInterrupt:
        pass
    finally:
        obs_pub.close()
        action_sub.close()
        env.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the simulator.")
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--log-level", default="INFO")
    parser.add_argument(
        "--max-steps", type=int, default=None, help="stop after N control steps (for testing)"
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=args.log_level, format="%(asctime)s %(name)s %(levelname)s %(message)s"
    )
    config = yaml.safe_load(args.config.read_text())
    run(config, max_steps=args.max_steps)


if __name__ == "__main__":
    main()
