"""Simulation process: steps physics, publishes observations, consumes action chunks.

Runs the control loop at env_config.yaml's control_hz. Physics never waits for
policy inference (see README architecture): each control step applies whatever
action is currently active -- a slice of the newest received ActionChunk, or a
safe fallback (hold the last commanded action) if nothing fresh enough has
arrived.

Also drains dashboard commands (reset/pause/resume/step/domain randomization)
and publishes a status snapshot each iteration -- see dashboard/server.py.
Both are non-blocking and additive: pulling this thread out entirely would
leave the sim<->policy loop this file's docstring describes completely intact.
"""

from __future__ import annotations

import argparse
import logging
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import yaml

# `generated/` (protoc output) isn't a declared package in pyproject.toml --
# it's regenerated by scripts/compile_proto.sh, not installed -- so running
# this file directly (`python scripts/run_sim.py`, as the README documents)
# needs the repo root on sys.path explicitly. `python -m` would add it
# automatically via cwd, but a plain script invocation only adds its own
# directory (scripts/), not the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sim.mujoco_env import MujocoManipulationEnv
from sim.zmq_publisher import (
    ActionChunkSubscriber,
    CommandSubscriber,
    ObservationPublisher,
    StatusPublisher,
    now_us,
)

logger = logging.getLogger("run_sim")

BLEND_STEPS = 4  # control steps to ramp into a newly arrived chunk
MAX_ACTION_AGE_US = 500_000  # 0.5s: older than this without a new chunk -> fallback
STATUS_PERIOD_S = 0.2  # snappier than the 1s text log, cheap since it's tiny JSON


class ActionChunkPlayer:
    """Tracks the active ActionChunk and produces one action per control step.

    Handles the two behaviors the README calls out explicitly: blending a
    newly arrived chunk into the one currently playing instead of jumping
    discontinuously, and falling back to holding the last commanded action
    when nothing fresh enough has arrived.
    """

    def __init__(self, action_dim: int) -> None:
        self.action_dim = action_dim
        self._last_action = np.zeros(action_dim, dtype=np.float32)
        self._chunk: dict[str, Any] | None = None
        self._chunk_step = 0
        self._blend_remaining = 0
        self.fallback_steps = 0

    def offer(self, chunk: dict[str, Any] | None) -> None:
        if chunk is None:
            return
        if self._chunk is not None and chunk["frame_id"] <= self._chunk["frame_id"]:
            return  # stale relative to what's already playing
        self._chunk = chunk
        self._chunk_step = 0
        self._blend_remaining = min(BLEND_STEPS, chunk["horizon"])

    def next_action(self) -> tuple[np.ndarray, bool]:
        """Returns (action, is_fallback)."""
        now = now_us()
        chunk_usable = (
            self._chunk is not None
            and self._chunk_step < self._chunk["horizon"]
            and (now - self._chunk["timestamp_us"]) <= MAX_ACTION_AGE_US
        )
        if not chunk_usable:
            self.fallback_steps += 1
            return self._last_action, True

        target = self._chunk["actions"][self._chunk_step]
        if self._blend_remaining > 0:
            alpha = (BLEND_STEPS - self._blend_remaining + 1) / BLEND_STEPS
            action = (1 - alpha) * self._last_action + alpha * target
            self._blend_remaining -= 1
        else:
            action = target
        self._chunk_step += 1
        self._last_action = action.astype(np.float32)
        return self._last_action, False

    @property
    def action_age_ms(self) -> float | None:
        if self._chunk is None:
            return None
        return (now_us() - self._chunk["timestamp_us"]) / 1_000


def _status(
    env: MujocoManipulationEnv,
    player: ActionChunkPlayer,
    *,
    control_hz: float,
    frame_id: int,
    is_fallback: bool,
    paused: bool,
) -> dict[str, Any]:
    return {
        "timestamp_us": now_us(),
        "control_hz": control_hz,
        "frame_id": frame_id,
        "action_age_ms": player.action_age_ms,
        "mode": "fallback" if is_fallback else "predicted",
        "fallback_steps": player.fallback_steps,
        "paused": paused,
        "domain_randomization_enabled": env.domain_randomization_enabled,
    }


def run(config: dict[str, Any], max_steps: int | None = None) -> None:
    env = MujocoManipulationEnv(config)
    ipc_cfg = config["ipc"]
    obs_pub = ObservationPublisher(
        ipc_cfg["observations"], high_water_mark=ipc_cfg["high_water_mark"]
    )
    action_sub = ActionChunkSubscriber(
        ipc_cfg["actions"], high_water_mark=ipc_cfg["high_water_mark"]
    )
    command_sub = CommandSubscriber(ipc_cfg["commands"])
    status_pub = StatusPublisher(ipc_cfg["status"])
    player = ActionChunkPlayer(action_dim=env.action_space.shape[0])

    control_period = 1.0 / config["control_hz"]
    obs, _ = env.reset()
    obs_pub.send(obs)

    paused = False
    step_once = False
    is_fallback = True
    achieved_hz = 0.0
    resuming = False  # true for the first step after a pause, to reset the Hz window

    step = 0
    last_log = time.perf_counter()
    last_status = time.perf_counter()
    steps_since_log = 0
    try:
        while max_steps is None or step < max_steps:
            loop_start = time.perf_counter()

            for command in command_sub.drain():
                ctype = command.get("type")
                if ctype == "reset":
                    obs, _ = env.reset()
                    obs_pub.send(obs)
                elif ctype == "pause":
                    paused = True
                elif ctype == "resume":
                    paused = False
                elif ctype == "step":
                    step_once = True
                elif ctype == "set_domain_randomization":
                    env.set_domain_randomization(bool(command.get("enabled", False)))
                else:
                    logger.warning("ignoring unknown command: %r", command)

            if paused and not step_once:
                now = time.perf_counter()
                if now - last_status >= STATUS_PERIOD_S:
                    status_pub.send(
                        _status(
                            env,
                            player,
                            control_hz=0.0,
                            frame_id=obs["frame_id"],
                            is_fallback=is_fallback,
                            paused=True,
                        )
                    )
                    last_status = now
                sleep_for = control_period - (time.perf_counter() - loop_start)
                if sleep_for > 0:
                    time.sleep(sleep_for)
                resuming = True  # next real step starts a fresh Hz-averaging window
                continue
            step_once = False

            if resuming:
                # Otherwise the Hz window's elapsed time would include however
                # long we were just paused, understating control_hz for one
                # log/status cycle even though nothing was actually slow.
                last_log = time.perf_counter()
                steps_since_log = 0
                resuming = False

            player.offer(action_sub.recv(timeout_ms=0))
            action, is_fallback = player.next_action()

            obs, _reward, terminated, truncated, _info = env.step(action)
            obs_pub.send(obs)

            step += 1
            steps_since_log += 1
            if terminated or truncated:
                obs, _ = env.reset()
                obs_pub.send(obs)

            now = time.perf_counter()
            if now - last_log >= 1.0:
                achieved_hz = steps_since_log / (now - last_log)
                logger.info(
                    "control_hz=%.1f frame_id=%d action_age_ms=%s mode=%s fallback_steps=%d",
                    achieved_hz,
                    obs["frame_id"],
                    player.action_age_ms,
                    "fallback" if is_fallback else "predicted",
                    player.fallback_steps,
                )
                last_log, steps_since_log = now, 0

            if now - last_status >= STATUS_PERIOD_S:
                status_pub.send(
                    _status(
                        env,
                        player,
                        control_hz=achieved_hz,
                        frame_id=obs["frame_id"],
                        is_fallback=is_fallback,
                        paused=False,
                    )
                )
                last_status = now

            sleep_for = control_period - (time.perf_counter() - loop_start)
            if sleep_for > 0:
                time.sleep(sleep_for)
    except KeyboardInterrupt:
        pass
    finally:
        obs_pub.close()
        action_sub.close()
        command_sub.close()
        status_pub.close()
        env.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the simulator.")
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--log-level", default="INFO")
    parser.add_argument(
        "--max-steps", type=int, default=None, help="stop after N control steps (for testing)"
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=args.log_level, format="%(asctime)s %(name)s %(levelname)s %(message)s"
    )
    config = yaml.safe_load(args.config.read_text())
    run(config, max_steps=args.max_steps)


if __name__ == "__main__":
    main()
